version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    tty: true
    volumes:
      - ./app:/go/src/app
    ports:
      - "8080:8080"
    working_dir: /go/src/app
