version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - "83:83"
    # depends_on:
    #   - app
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    tty: true
    volumes:
      - ./app:/go/src/app
    ports:
      - "3006:3006"
    working_dir: /go/src/app
